# Generated by Django 3.2.9 on 2021-11-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_item',
            fields=[
                ('item_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
