# Generated by Django 3.2.9 on 2021-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_rename_inventory_item_inventory_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_items',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
